# Generated by Django 6.0.1 on 2026-01-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('letter_no', models.CharField(max_length=200)),
                ('date_received', models.DateField()),
                ('mail_reference_subject', models.TextField()),
                ('from_office', models.CharField(max_length=200)),
                ('action_required', models.CharField(choices=[('Review', 'Review'), ('Approve', 'Approve'), ('Process', 'Process'), ('File', 'File'), ('Reply', 'Reply'), ('Other', 'Other')], max_length=50)),
                ('action_required_other', models.CharField(blank=True, max_length=200, null=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Received', max_length=20)),
                ('date_of_completion', models.DateField(blank=True, null=True)),
                ('last_status_change', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
