# Generated by Django 6.0.1 on 2026-01-20 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        ('sections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailrecord',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_mails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_mails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailrecord',
            name='current_handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_mails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailrecord',
            name='monitoring_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitored_mails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailrecord',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mails', to='sections.section'),
        ),
    ]
