# Generated by Django 6.0.1 on 2026-01-21 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_mailrecord_date_received_and_more'),
        ('sections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mailrecord',
            index=models.Index(fields=['status'], name='records_mai_status_4962d5_idx'),
        ),
        migrations.AddIndex(
            model_name='mailrecord',
            index=models.Index(fields=['section'], name='records_mai_section_c4fbc9_idx'),
        ),
        migrations.AddIndex(
            model_name='mailrecord',
            index=models.Index(fields=['current_handler'], name='records_mai_current_4c40b4_idx'),
        ),
        migrations.AddIndex(
            model_name='mailrecord',
            index=models.Index(fields=['assigned_to'], name='records_mai_assigne_4966bc_idx'),
        ),
        migrations.AddIndex(
            model_name='mailrecord',
            index=models.Index(fields=['due_date'], name='records_mai_due_dat_40e774_idx'),
        ),
        migrations.AddIndex(
            model_name='mailrecord',
            index=models.Index(fields=['created_at'], name='records_mai_created_c8e8ef_idx'),
        ),
        migrations.AddIndex(
            model_name='mailrecord',
            index=models.Index(fields=['section', 'status'], name='records_mai_section_59a052_idx'),
        ),
    ]
