# Generated by Django 6.0.1 on 2026-01-21 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailrecord',
            name='consolidated_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailrecord',
            name='is_multi_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MailAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_remarks', models.TextField(blank=True, null=True)),
                ('user_remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Revoked', 'Revoked')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parallel_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parallel_assigned_mails', to=settings.AUTH_USER_MODEL)),
                ('mail_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parallel_assignments', to='records.mailrecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mail_record', 'status'], name='records_mai_mail_re_f2e2f4_idx'), models.Index(fields=['assigned_to', 'status'], name='records_mai_assigne_17ddfd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'Active')), fields=('mail_record', 'assigned_to'), name='unique_active_assignment_per_user')],
            },
        ),
    ]
