# Generated by Django 6.0.1 on 2026-01-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_add_multi_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailrecord',
            name='initial_instructions',
            field=models.TextField(blank=True, help_text='Initial instructions from creator, visible to all assignees', null=True),
        ),
        migrations.AlterField(
            model_name='mailrecord',
            name='consolidated_remarks',
            field=models.TextField(blank=True, help_text='Auto-generated from all assignment remarks', null=True),
        ),
        migrations.AlterField(
            model_name='mailrecord',
            name='remarks',
            field=models.TextField(blank=True, help_text='DEPRECATED: Use initial_instructions or assignment-level remarks', null=True),
        ),
    ]
