# Generated by Django 6.0.1 on 2026-01-25 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_add_initial_instructions'),
        ('sections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailassignment',
            name='reassigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailassignment',
            name='reassigned_to',
            field=models.ForeignKey(blank=True, help_text='If assignee reassigned to another officer, track the new person', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reassigned_from_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mailrecord',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Section owning this mail. Null for cross-section multi-assignments.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mails', to='sections.section'),
        ),
        migrations.CreateModel(
            name='AssignmentRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks_timeline', to='records.mailassignment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_remarks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['assignment', 'created_at'], name='records_ass_assignm_cf78f2_idx')],
            },
        ),
    ]
