# Generated by Django 5.2.11 on 2026-02-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_multi_assignment_workflow_v2'),
        ('sections', '0002_section_directly_under_ag_subsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailrecord',
            name='subsection',
            field=models.ForeignKey(blank=True, help_text='Subsection within the section (optional, used when assigned to SrAO/AAO)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mails', to='sections.subsection'),
        ),
    ]
