# Generated by Django 5.2.11 on 2026-02-14 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_mailrecord_subsection'),
        ('sections', '0002_section_directly_under_ag_subsection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailrecord',
            name='current_action_remarks',
            field=models.TextField(blank=True, help_text='Optional details about the current action being performed', null=True),
        ),
        migrations.AddField(
            model_name='mailrecord',
            name='current_action_status',
            field=models.CharField(blank=True, choices=[('Under Review', 'Under Review'), ('Drafting Reply', 'Drafting Reply'), ('Seeking Clarification', 'Seeking Clarification'), ('Awaiting Information', 'Awaiting Information'), ('Processing', 'Processing'), ('Finalizing', 'Finalizing'), ('On Hold', 'On Hold'), ('Consulting', 'Consulting'), ('Verification', 'Verification')], help_text='What the current handler is actively doing with this mail', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mailrecord',
            name='current_action_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the current action status was last updated', null=True),
        ),
        migrations.AddIndex(
            model_name='mailrecord',
            index=models.Index(fields=['current_action_status'], name='records_mai_current_042843_idx'),
        ),
    ]
