# Generated by Django 5.2.11 on 2026-02-20 03:57

import django.db.models.deletion
import records.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_mailrecord_current_action_remarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailrecord',
            name='current_action_status',
            field=models.CharField(blank=True, choices=[('Under Review', 'Under Review'), ('Drafting Reply', 'Drafting Reply'), ('Seeking Clarification', 'Seeking Clarification'), ('Awaiting Information', 'Awaiting Information'), ('Processing', 'Processing'), ('Finalizing', 'Finalizing'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Consulting', 'Consulting'), ('Verification', 'Verification')], help_text='What the current handler is actively doing with this mail', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='RecordAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, upload_to=records.models.pdf_upload_path, validators=[records.models.validate_pdf_extension, records.models.validate_pdf_size])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True, help_text='False when superseded by a replacement')),
                ('mail_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='records.mailrecord')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Record Attachment',
                'verbose_name_plural': 'Record Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
