# Generated by Django 5.2.11 on 2026-02-20 04:03

import records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_add_recordattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordattachment',
            name='upload_stage',
            field=models.CharField(choices=[('created', 'Created'), ('closed', 'Closed')], default='created', help_text='Workflow stage at which this PDF was uploaded', max_length=10),
        ),
        migrations.AlterField(
            model_name='recordattachment',
            name='file',
            field=models.FileField(max_length=255, storage=records.models.get_pdf_storage, upload_to=records.models.pdf_upload_path, validators=[records.models.validate_pdf_extension, records.models.validate_pdf_size]),
        ),
        migrations.AlterField(
            model_name='recordattachment',
            name='is_current',
            field=models.BooleanField(default=True, help_text='False when superseded by a replacement for the same stage'),
        ),
    ]
