# Generated by Django 5.2.11 on 2026-02-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_add_upload_stage_to_recordattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailrecord',
            name='action_required',
            field=models.CharField(blank=True, help_text='What action is required on this mail (free text, optional, max 500 chars)', max_length=500),
        ),
    ]
