# Generated by Django 5.2.11 on 2026-02-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_action_required_free_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentremark',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mailassignment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mailassignment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Revoked', 'Revoked')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='mailrecord',
            name='action_required_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mailrecord',
            name='current_action_status',
            field=models.CharField(blank=True, choices=[('Under Review', 'Under Review'), ('Drafting Reply', 'Drafting Reply'), ('Seeking Clarification', 'Seeking Clarification'), ('Awaiting Information', 'Awaiting Information'), ('Processing', 'Processing'), ('Finalizing', 'Finalizing'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Consulting', 'Consulting'), ('Verification', 'Verification')], help_text='What the current handler is actively doing with this mail', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mailrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mailrecord',
            name='sl_no',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='mailrecord',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Received', max_length=15),
        ),
        migrations.AlterField(
            model_name='recordattachment',
            name='upload_stage',
            field=models.CharField(choices=[('created', 'Created'), ('closed', 'Closed')], default='created', help_text='Workflow stage at which this PDF was uploaded', max_length=7),
        ),
    ]
