# Generated by Django 5.2.11 on 2026-02-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_alter_assignmentremark_id_alter_mailassignment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailassignment',
            name='user_remarks',
        ),
        migrations.RemoveField(
            model_name='mailrecord',
            name='action_required_other',
        ),
        migrations.RemoveField(
            model_name='mailrecord',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='mailrecord',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Created', max_length=15),
        ),
    ]
