# Generated by Django 5.2.11 on 2026-02-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='directly_under_ag',
            field=models.BooleanField(default=False, help_text='Check if this section reports directly to AG (no DAG)'),
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='sections.section')),
            ],
            options={
                'ordering': ['section__name', 'name'],
                'unique_together': {('section', 'name')},
            },
        ),
    ]
