# Generated by Django 5.2.11 on 2026-02-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_section_directly_under_ag_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
