# Generated by Django 5.2.11 on 2026-02-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_section_directly_under_ag_subsection'),
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='section',
        ),
        migrations.AddField(
            model_name='user',
            name='sections',
            field=models.ManyToManyField(blank=True, help_text='Sections managed by this DAG (only for DAG role)', related_name='dags', to='sections.section'),
        ),
        migrations.AddField(
            model_name='user',
            name='subsection',
            field=models.ForeignKey(blank=True, help_text='Subsection for SrAO/AAO officers', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_officers', to='sections.subsection'),
        ),
    ]
