# Generated by Django 5.2.11 on 2026-02-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_section_user_sections_user_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AG', 'Accountant General'), ('DAG', 'Deputy Accountant General'), ('SrAO', 'Senior Audit Officer'), ('AAO', 'Assistant Audit Officer')], max_length=10),
        ),
    ]
