# Generated by Django 5.2.11 on 2026-02-20 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_section_directly_under_ag_subsection'),
        ('users', '0006_set_primary_ag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auditor_subsections',
            field=models.ManyToManyField(blank=True, help_text="Subsections visible to this auditor (configured by admin). Only used when role='auditor'.", related_name='auditors', to='sections.subsection'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AG', 'Accountant General'), ('DAG', 'Deputy Accountant General'), ('SrAO', 'Senior Audit Officer'), ('AAO', 'Assistant Audit Officer'), ('auditor', 'Auditor'), ('clerk', 'Clerk')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='subsection',
            field=models.ForeignKey(blank=True, help_text='Subsection for SrAO/AAO/clerk officers', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_officers', to='sections.subsection'),
        ),
    ]
