# Generated by Django 5.2.11 on 2026-03-05 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_alter_section_id_alter_section_name_and_more'),
        ('users', '0008_alter_user_full_name_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=128)),
                ('requested_role', models.CharField(choices=[('SrAO', 'Senior Audit Officer'), ('AAO', 'Assistant Audit Officer'), ('auditor', 'Auditor'), ('clerk', 'Clerk')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_signup_requests', to=settings.AUTH_USER_MODEL)),
                ('processed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_signup_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_requests', to='sections.section')),
                ('requested_subsection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_requests', to='sections.subsection')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='users_signu_status_48d79c_idx'), models.Index(fields=['username'], name='users_signu_usernam_f2f055_idx'), models.Index(fields=['email'], name='users_signu_email_fc7c65_idx')],
            },
        ),
    ]
