# Generated by Django 5.2.11 on 2026-03-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_signuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='actual_role',
            field=models.CharField(blank=True, default='', help_text='Display role/title shown in UI (functional permissions still use role).', max_length=100),
        ),
    ]
