# Generated by Django 6.0.1 on 2026-01-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audittrail',
            options={'ordering': ['timestamp']},
        ),
    ]
