# Generated by Django 6.0.1 on 2026-01-21 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_audittrail_options'),
        ('records', '0003_alter_mailrecord_date_received_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['mail_record', 'performed_by'], name='audit_audit_mail_re_c2154d_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['performed_by'], name='audit_audit_perform_602f00_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['mail_record'], name='audit_audit_mail_re_0250d9_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['timestamp'], name='audit_audit_timesta_061303_idx'),
        ),
    ]
