# Generated by Django 6.0.1 on 2026-01-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('ASSIGN', 'Assigned'), ('REASSIGN', 'Reassigned'), ('UPDATE', 'Added remarks'), ('CLOSE', 'Closed'), ('REOPEN', 'Reopened'), ('MULTI_ASSIGN', 'Assigned to Multiple'), ('ASSIGNMENT_UPDATE', 'Assignment Updated'), ('ASSIGNMENT_COMPLETE', 'Assignment Completed'), ('ASSIGNMENT_REVOKE', 'Assignment Revoked')], max_length=20),
        ),
    ]
