# Generated by Django 5.2.11 on 2026-02-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_alter_audittrail_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('ASSIGN', 'Assigned'), ('REASSIGN', 'Reassigned'), ('UPDATE', 'Added remarks'), ('CLOSE', 'Closed'), ('REOPEN', 'Reopened'), ('MULTI_ASSIGN', 'Assigned to Multiple'), ('ASSIGNMENT_UPDATE', 'Assignment Updated'), ('ASSIGNMENT_COMPLETE', 'Assignment Completed'), ('ASSIGNMENT_REVOKE', 'Assignment Revoked'), ('PDF_UPLOAD', 'PDF Uploaded'), ('PDF_REPLACE', 'PDF Replaced'), ('PDF_DELETE', 'PDF Deleted')], max_length=20),
        ),
    ]
